"use client";
import { FormEvent, useEffect, useState } from 'react';
import Shell from '../../components/Shell';
import { api } from '../../lib';

const ruleTypes = [
  ['MODULE_PASS_MARK','Seuil de validation du module'],['SEMESTER_PASS_MARK','Seuil de validation du semestre'],['ELIMINATORY_MARK','Note éliminatoire'],
  ['COMPENSATION_ALLOWED','Compensation autorisée'],['RESIT_ALLOWED','Rattrapage autorisé'],['CAPITALIZATION_ALLOWED','Capitalisation autorisée']
];

export default function Page(){
  const [programs,setPrograms]=useState<any[]>([]),[modules,setModules]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[levels,setLevels]=useState<any[]>([]),[semesters,setSemesters]=useState<any[]>([]),[elements,setElements]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[error,setError]=useState('');
  const [level,setLevel]=useState<any>({}),[semester,setSemester]=useState<any>({}),[element,setElement]=useState<any>({coefficient:1,volumeHours:0}),[rule,setRule]=useState<any>({});
  async function load(){const [p,m,t,l,s,e,r]=await Promise.all([api('/programs'),api('/academic-modules'),api('/teachers'),api('/academic-structure/levels'),api('/academic-structure/semesters'),api('/academic-structure/elements'),api('/academic-structure/validation-rules')]);setPrograms(p);setModules(m);setTeachers(t);setLevels(l);setSemesters(s);setElements(e);setRules(r)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submit(path:string,data:any,setter:(v:any)=>void,e:FormEvent){e.preventDefault();setError('');try{await api(path,{method:'POST',body:JSON.stringify(data)});setter({});await load()}catch(err:any){setError(err.message)}}
  const booleanRule = ['COMPENSATION_ALLOWED','RESIT_ALLOWED','CAPITALIZATION_ALLOWED'].includes(rule.type);
  return <Shell><div className="page-head"><div><h1>Structure académique</h1><div className="muted">Niveaux, semestres, éléments de module et règles pédagogiques configurables.</div></div></div>{error&&<div className="error">{error}</div>}
  <div className="two-col">
    <div className="panel"><h2>Niveaux</h2><form onSubmit={e=>submit('/academic-structure/levels',level,setLevel,e)}><div className="field"><label>Filière</label><select required value={level.programId||''} onChange={e=>setLevel({...level,programId:e.target.value})}><option value="">Sélectionner</option>{programs.map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="field"><label>Numéro du niveau</label><input type="number" min="1" required value={level.levelNumber||''} onChange={e=>setLevel({...level,levelNumber:e.target.value})}/></div><div className="field"><label>Code</label><input required value={level.code||''} onChange={e=>setLevel({...level,code:e.target.value})}/></div><div className="field"><label>Nom</label><input required value={level.name||''} onChange={e=>setLevel({...level,name:e.target.value})}/></div><button className="btn btn-primary">Ajouter le niveau</button></form><div className="compact-list">{levels.map(x=><div key={x.id}><strong>{x.program?.code} · {x.code}</strong><span>{x.name}</span></div>)}</div></div>
    <div className="panel"><h2>Semestres</h2><form onSubmit={e=>submit('/academic-structure/semesters',semester,setSemester,e)}><div className="field"><label>Niveau</label><select required value={semester.levelId||''} onChange={e=>setSemester({...semester,levelId:e.target.value})}><option value="">Sélectionner</option>{levels.map(x=><option value={x.id} key={x.id}>{x.program?.code} · {x.name}</option>)}</select></div><div className="field"><label>Ordre</label><input type="number" min="1" required value={semester.ordinal||''} onChange={e=>setSemester({...semester,ordinal:e.target.value})}/></div><div className="field"><label>Code</label><input required value={semester.code||''} onChange={e=>setSemester({...semester,code:e.target.value})}/></div><div className="field"><label>Nom</label><input required value={semester.name||''} onChange={e=>setSemester({...semester,name:e.target.value})}/></div><button className="btn btn-primary">Ajouter le semestre</button></form><div className="compact-list">{semesters.map(x=><div key={x.id}><strong>{x.level?.program?.code} · {x.code}</strong><span>{x.level?.name} · {x.name}</span></div>)}</div></div>
  </div>
  <div className="two-col">
    <div className="panel"><h2>Éléments de module</h2><form onSubmit={e=>submit('/academic-structure/elements',element,setElement,e)}><div className="field"><label>Module</label><select required value={element.moduleId||''} onChange={e=>setElement({...element,moduleId:e.target.value})}><option value="">Sélectionner</option>{modules.map(x=><option value={x.id} key={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="field"><label>Code</label><input required value={element.code||''} onChange={e=>setElement({...element,code:e.target.value})}/></div><div className="field"><label>Nom</label><input required value={element.name||''} onChange={e=>setElement({...element,name:e.target.value})}/></div><div className="field"><label>Coefficient</label><input type="number" step="0.1" value={element.coefficient??1} onChange={e=>setElement({...element,coefficient:e.target.value})}/></div><div className="field"><label>Volume horaire</label><input type="number" step="0.5" value={element.volumeHours??0} onChange={e=>setElement({...element,volumeHours:e.target.value})}/></div><div className="field"><label>Enseignant</label><select value={element.teacherId||''} onChange={e=>setElement({...element,teacherId:e.target.value})}><option value="">Non affecté</option>{teachers.map(x=><option value={x.id} key={x.id}>{x.lastName} {x.firstName}</option>)}</select></div><button className="btn btn-primary">Ajouter l’élément</button></form><div className="compact-list">{elements.map(x=><div key={x.id}><strong>{x.module?.code} / {x.code}</strong><span>{x.name} · {x.volumeHours} h</span></div>)}</div></div>
    <div className="panel"><h2>Règles de validation</h2><form onSubmit={e=>submit('/academic-structure/validation-rules',rule,setRule,e)}><div className="field"><label>Filière</label><select value={rule.programId||''} onChange={e=>setRule({...rule,programId:e.target.value})}><option value="">Globale</option>{programs.map(x=><option value={x.id} key={x.id}>{x.code}</option>)}</select></div><div className="field"><label>Niveau</label><select value={rule.levelId||''} onChange={e=>setRule({...rule,levelId:e.target.value})}><option value="">Tous niveaux</option>{levels.filter(x=>!rule.programId||x.program?.id===rule.programId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Règle</label><select required value={rule.type||''} onChange={e=>setRule({...rule,type:e.target.value})}><option value="">Sélectionner</option>{ruleTypes.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></div>{booleanRule?<div className="field"><label>Valeur</label><select value={String(rule.booleanValue??'')} onChange={e=>setRule({...rule,booleanValue:e.target.value})}><option value="">Sélectionner</option><option value="true">Oui</option><option value="false">Non</option></select></div>:<div className="field"><label>Valeur numérique</label><input type="number" step="0.01" value={rule.numericValue||''} onChange={e=>setRule({...rule,numericValue:e.target.value})}/></div>}<button className="btn btn-primary">Ajouter la règle</button></form><div className="compact-list">{rules.map(x=><div key={x.id}><strong>{x.type}</strong><span>{x.level?.name||x.program?.code||'Globale'} · {x.numericValue??(x.booleanValue?'Oui':'Non')}</span></div>)}</div></div>
  </div></Shell>;
}
